apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: prometheus
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['10.1.1.67:8888']       # kubectl describe pod [spring pod 이름]의 ip 주소로 수정

      - job_name: jenkins
        metrics_path: '/prometheus/'
        static_configs:
          - targets: ['083f-183-109-114-170.ngrok-free.app']
        scheme: https